pipeline {
    agent any

    environment {
        DOCKER_HUB_REPO = 'essy09/abc-retail-app'
        DOCKER_HUB_CREDENTIALS = 'DOCKER_HUB_PWD'
        KUBERNETES_CONFIG = '/root/.kube/config'
        ANSIBLE_PLAYBOOK_PATH = '/root/industry-devops-project/ABC Technologies/deploy/deploy.yml'
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Cloning the repository...'
                git url: 'https://github.com/EstherTimbwa/industry-devops-project.git', branch: 'master'
            }
        }

        stage('Build Application') {
            steps {
                echo 'Building the application...'
                sh 'mvn clean compile -x'  // Enable debug for Maven
            }
        }

        stage('Test Application') {
            steps {
                echo 'Running tests...'
                sh 'mvn test -x'  // Enable debug for Maven
            }
        }

        stage('Package Application') {
            steps {
                echo 'Packaging the application...'
                sh 'mvn package -x'  // Enable debug for Maven
                archiveArtifacts artifacts: 'target/*.war', fingerprint: true
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                echo 'Building and pushing Docker image...'
                script {
                    sh '''
                    docker build -t essy09/abc-retail-app:latest .
                    docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
                    docker push essy09/abc-retail-app:latest
                    '''
                }
            }
        }

        stage('Deploy with Ansible') {
            steps {
                echo 'Deploying with Ansible...'
                ansiblePlaybook installation: 'Ansible', playbook: ANSIBLE_PLAYBOOK_PATH
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                echo 'Deploying to Kubernetes...'
                script {
                    sh '''
                    export KUBECONFIG=$KUBERNETES_CONFIG
                    kubectl apply -f deployment.yml
                    kubectl apply -f service.yml
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs for details.'
        }
    }
}
