pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'master', url: 'https://github.com/EstherTimbwa/industry-devops-project.git'
            }
        }
        stage('Deploy to GCP') {
            steps {
                sshagent(credentials: ['SHA256:p4pnA69rQ0Txkd8wlFZTXqDpbq3Fb92CXdtBMcgtQhQ jenkins-deploy']) {
                    sh '''
                    # Copy the HTML file to the GCP instance
                    scp -o StrictHostKeyChecking=no index.html <devopsdemo>@<35.236.250.35>:/var/www/html/
                    '''
                }
            }
        }
    }
}
