pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'master', url: 'https://github.com/EstherTimbwa/industry-devops-project.git'
            }
        }
        stage('Deploy to GCP') {
            steps {
                sshagent(['a62e3b2d-ef75-49ae-936e-8726be843a9a']) { //credential ID
                    sh '''
                    # Copy the index.html file to the remote server
                    scp -o StrictHostKeyChecking=no index.html devopsdemo@35.236.250.35:/var/www/html/
                    '''
                }
            }
        }
    }
}
