pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'master', url: 'https://github.com/EstherTimbwa/industry-devops-project.git'
            }
        }
        stage('Deploy to GCP') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'DOCKER_HUB_LOGIN', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''
                    # Using username and password to authenticate for SCP
                    sshpass -p "$PASSWORD" scp -o StrictHostKeyChecking=no index.html $USERNAME@35.236.250.35:/var/www/html/
                    '''
                }
            }
        }
    }
}
